"use client";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { useEffect, useState } from "react";
import Error from "../ui/Error"
import Loading from "../ui/Loading"


// Initialize the API client
const genAI = new GoogleGenerativeAI( "AIzaSyB-9YvbpoxsCp6uI6gtRiL_5sL_hzrGUuk" || localStorage.getItem("api") );

export async function makeChatRequest(promptInput) {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContent(promptInput);

    let responseText = result.response.candidates[0].content.parts[0].text;
    responseText = responseText
      .replace(/^```json[\r\n]*/, "")
      .replace(/```[\r\n]*$/, "")
      .trim();

    console.log("Generated Response:", responseText);

    return JSON.parse(responseText);
  } catch (error) {
    console.error("Error generating text:", error);
    throw error;
  }
}

async function getResult(languages, frameworks) {
  let prompt = `Give me the JSON for an array object called "paths" containing 10 learning paths that suggest user for learning new programming skills which are related to what he knows. Paths should be in the form of objects which have title, description and skills (new or old) as keys. The user knows [${languages}] language(s).`;
  if (frameworks) {
    prompt += ` The user knows [${frameworks}] frameworks.`;
  }

  return await makeChatRequest(prompt)
    .then((res) => {
      console.log("AI Response Paths:", res);
      return res.paths || [];
    })
    .catch((err) => {
      console.error("Error in getResult:", err);
      return [];
    });
}

function Result({ paths }) {
  return (
    <div className="container-fluid mt-5 text-center">
  {/* Title */}
  <h1 className="fw-semibold fs-2 text-dark">Projects You Can Build</h1>
  <p className="text-muted mx-auto w-75">
    These are the paths generated by the AI. Please note that these suggestions are for 
    learning purposes and may not be guaranteed to be 100% accurate.
  </p>

  {/* Grid Layout */}
  <div className="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 p-2 mt-2">
    {paths.map((path, index) => (
      <div className="col" key={index}>
        <div className="card border-1 shadow-sm p-3 h-100">
          {/* Project Title */}
          <h2 className="fs-4 fw-bold text-dark">{path.title}</h2>
          {/* Description */}
          <p className="text-muted">{path.description}</p>
          {/* Skills List */}
          <div className="d-flex flex-wrap justify-content-center gap-2">
            {path.skills.map((skill, index) => (
              <span className="badge bg-secondary text-light rounded-pill px-3 py-2" key={index}>
                {skill}
              </span>
            ))}
          </div>
        </div>
      </div>
    ))}
  </div>
</div>

  );
}

export default function ProjectIdea() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      if (sessionStorage.getItem("userKnowledge")) {
        try {
          const userKnowledge = JSON.parse(
            sessionStorage.getItem("userKnowledge")
          );
          console.log("User Knowledge:", userKnowledge);

          const result = await getResult(
            userKnowledge.lang,
            userKnowledge.framework
          );
          console.log("Paths Data:", result);

          if (result.length > 0) {
            setData(result);
          } else {
            console.error("No paths found.");
            setError("No paths found.");
          }
        } catch (err) {
          console.error("Error fetching data:", err);
          setError("Error fetching data.");
        }
      } else {
        console.error("No user knowledge found in sessionStorage.");
        setError("No user knowledge found.");
      }
    };

    fetchData();
  }, []);

  if (error) {
    return (
      <Error message={error} />
    );
  }

  return (
    <main className="max-w-7xl mx-auto px-8 sm:px-16 w-screen">
      <div className="flex flex-col items-center h-full gap-10 justify-center">
        {data ? <Result paths={data} /> : <Loading />}
      </div>
    </main>
  );
}
